name: liwe3
description: "The LiWE3 Official Flutter library"

homepage: https://www.liwe3.org
repository: https://github.com/fsoft72/liwe3_flutter

platforms:
  android:
  ios:

version: 0.0.4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.3
  get: ^4.6.6

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: it.os3.liwe3
    iosBundleIdentifier: it.os3.liwe3
