name: liwe3
description: "The LiWE3 Official Flutter library"

homepage: https://www.liwe3.org
repository: https://github.com/fsoft72/liwe3_flutter

#platforms:
#  android:
#  ios:

version: 0.2.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.3
  get: ^4.6.6
  encrypt: ^5.0.3
  path_provider: ^2.1.3
  flutter_markdown: ^0.7.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true