name: liwe3
description: "The LiWE3 Official Flutter library"

homepage: https://www.liwe3.org
repository: https://github.com/fsoft72/liwe3_flutter

platforms:
  android:
  ios:

version: 0.1.4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.3
  get: ^4.6.6
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  path_provider: ^2.1.3

  # Firebase Files
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^15.1.1
  cloud_firestore: ^4.17.3
  flutter_markdown: ^0.7.1

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: it.os3.liwe3
    iosBundleIdentifier: it.os3.liwe3
